Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -27,6 +27,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ needs.determine-environment.outputs.environment }}
     env:
+      DEPLOY_ENV : ${{ needs.determine-environment.outputs.environment }}
       EC2_HOST: ${{ vars.EC2_HOST }}
       EC2_USER: ${{ vars.EC2_USER }}
 
@@ -34,7 +35,7 @@ jobs:
     # Step 0: Log EC2_HOST and EC2_USER
       - name: Log deployment variables
         run: |
-          echo "Deployment variables for ${{ needs.determine-environment.outputs.environment }} environment:"
+          echo "DEPLOY_ENV: $DEPLOY_ENV"
           echo "EC2_HOST: $EC2_HOST"
           echo "EC2_USER: $EC2_USER"
       
@@ -60,7 +61,7 @@ jobs:
           context: .
           file: ./Dockerfile
           push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.event.inputs.environment }}-${{ github.sha }}
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$DEPLOY_ENV-${{ github.sha }}
 
       # Step 5: Deploy to EC2 via SSH
       - name: Deploy to EC2
@@ -79,7 +80,7 @@ jobs:
             sudo docker stop my-app-container || { echo "Failed to stop container"; exit 1; }
             sudo docker rm my-app-container || { echo "Failed to remove container"; exit 1; }
             echo "Pulling latest image"
-            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.event.inputs.environment }}-${{ github.sha }} || { echo "Docker pull failed"; exit 1; }
+            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:$DEPLOY_ENV-${{ github.sha }} || { echo "Docker pull failed"; exit 1; }
             echo "Running new container"
             sudo docker run -d --name my-app-container -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.event.inputs.environment }}-${{ github.sha }} || { echo "Docker run failed"; exit 1; }
             echo "Cleaning up unused images"
